Style/FrozenStringLiteralComment:
  Enabled: false
Style/HashEachMethods:
  Enabled: false
Style/HashTransformKeys:
  Enabled: false
Style/HashTransformValues:
  Enabled: false
Metrics/LineLength:
  Enabled: false
  Max: 150
AllCops:
  Exclude:
    - app/views/**/*.*.builder
    - 'bin/*'
    - 'config/**/*.rb'
    - 'db/**/*.rb'
    - 'lib/**/*.*'
    - 'log/**/*.*'
    - 'node_modules/**/*'
    - 'public/**/*'
    - 'spec/**/*.rb'
    - 'tmp/**/*.*'
    - 'vendor/**/*'
    - 'webapp/**/*'
    - 'Rakefile'
    - '**/*.rake'
    - greatest_hits.rb
    - bench_rails_memory_usage.rb
