# .rubocop.yml
require:
  - rubocop-rails
  - 'test_prof/rubocop'
AllCops:
  NewCops: enable
  Exclude:
    - app/controllers/*csv.rb
    - app/views/**/*.*.builder
    - 'bin/*'
    - 'config/**/*.rb'
    - 'db/**/*.rb'
    - 'lib/**/*.*'
    - 'log/**/*.*'
    - 'node_modules/**/*'
    - 'public/**/*'
    - 'spec/**/*.rb'
    - 'tmp/**/*.*'
    - 'vendor/**/*'
    - 'webapp/**/*'
    - 'Rakefile'
    - '**/*.rake'
    - greatest_hits.rb
    - bench_rails_memory_usage.rb
Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true
Layout/LineLength:
  Enabled: false
  Max: 150
Layout/SpaceAroundMethodCallOperator:
  Enabled: true
Lint/DeprecatedOpenSSLConstant:
  Enabled: true
Lint/InterpolationCheck:
  Enabled: false
Lint/MixedRegexpCaptureTypes:
  Enabled: true
Lint/RaiseException:
  Enabled: true
Lint/RescueException:
  Enabled: false
Lint/StructNewOverride:
  Enabled: true
Lint/SuppressedException:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Max: 35
Metrics/ClassLength:
  Max: 400
Metrics/CyclomaticComplexity:
  Max: 30
Metrics/MethodLength:
  Enabled: false
  Max: 20
Metrics/PerceivedComplexity:
  Enabled: false
Style/AndOr:
  Enabled: false
Style/ExpandPathArguments:
  Enabled: false
Style/ExponentialNotation:
    Enabled: true
Style/FrozenStringLiteralComment:
  Enabled: false
Style/HashEachMethods:
  Enabled: false
Style/HashTransformKeys:
  Enabled: false
Style/HashTransformValues:
  Enabled: false
Style/RedundantRegexpCharacterClass:
  Enabled: true
Style/RedundantRegexpEscape:
  Enabled: true
Style/RescueStandardError:
  Enabled: false
Style/SlicingWithRange:
  Enabled: true
