# Be sure to restart your server when you modify this file.

# Add new inflection rules using the following format. Inflections
# are locale specific, and you may define rules for as many different
# locales as you wish. All of these examples are active by default:
# ActiveSupport::Inflector.inflections(:en) do |inflect|
#   inflect.plural /^(ox)$/i, '\1en'
#   inflect.singular /^(ox)en/i, '\1'
#   inflect.irregular 'person', 'people'
#   inflect.uncountable %w( fish sheep )
# end

# These inflection rules are supported but not enabled by default:
# ActiveSupport::Inflector.inflections(:en) do |inflect|
#   inflect.acronym 'RESTful'
# end

ActiveSupport::Inflector.inflections(:'en-GB') do |inflect|
  inflect.uncountable %w( equipment information rice money species series fish sheep jeans police )
  inflect.singular /(?i-mx:(z)ombies$)/, '\1ombie'
  inflect.singular /(?i-mx:(z)ombie$)/, '\1ombie'
  inflect.singular /(?i-mx:(m)oves$)/, '\1ove'
  inflect.singular /(?i-mx:(m)ove$)/, '\1ove'
  inflect.singular /(?i-mx:(s)exes$)/, '\1ex'
  inflect.singular /(?i-mx:(s)ex$)/, '\1ex'
  inflect.singular /(?i-mx:(c)hildren$)/, '\1hild'
  inflect.singular /(?i-mx:(c)hild$)/, '\1hild'
  inflect.singular /(?i-mx:(m)en$)/, '\1an'
  inflect.singular /(?i-mx:(m)an$)/, '\1an'
  inflect.singular /(?i-mx:(p)eople$)/, '\1erson'
  inflect.singular /(?i-mx:(p)erson$)/, '\1erson'
  inflect.singular /(?i-mx:(database)s$)/, '\1'
  inflect.singular /(?i-mx:(quiz)zes$)/, '\1'
  inflect.singular /(?i-mx:(matr)ices$)/, '\1ix'
  inflect.singular /(?i-mx:(vert|ind)ices$)/, '\1ex'
  inflect.singular /(?i-mx:^(ox)en)/, '\1'
  inflect.singular /(?i-mx:(alias|status)(es)?$)/, '\1'
  inflect.singular /(?i-mx:(octop|vir)(us|i)$)/, '\1us'
  inflect.singular /(?i-mx:^(a)x[ie]s$)/, '\1xis'
  inflect.singular /(?i-mx:(cris|test)(is|es)$)/, '\1is'
  inflect.singular /(?i-mx:(shoe)s$)/, '\1'
  inflect.singular /(?i-mx:(o)es$)/, '\1'
  inflect.singular /(?i-mx:(bus)(es)?$)/, '\1'
  inflect.singular /(?i-mx:^(m|l)ice$)/, '\1ouse'
  inflect.singular /(?i-mx:(x|ch|ss|sh)es$)/, '\1'
  inflect.singular /(?i-mx:(m)ovies$)/, '\1ovie'
  inflect.singular /(?i-mx:(s)eries$)/, '\1eries'
  inflect.singular /(?i-mx:([^aeiouy]|qu)ies$)/, '\1y'
  inflect.singular /(?i-mx:([lr])ves$)/, '\1f'
  inflect.singular /(?i-mx:(tive)s$)/, '\1'
  inflect.singular /(?i-mx:(hive)s$)/, '\1'
  inflect.singular /(?i-mx:([^f])ves$)/, '\1fe'
  inflect.singular /(?i-mx:(^analy)(sis|ses)$)/, '\1sis'
  inflect.singular /(?i-mx:((a)naly|(b)a|(d)iagno|(p)arenthe|(p)rogno|(s)ynop|(t)he)(sis|ses)$)/, '\1sis'
  inflect.singular /(?i-mx:([ti])a$)/, '\1um'
  inflect.singular /(?i-mx:(n)ews$)/, '\1ews'
  inflect.singular /(?i-mx:(ss)$)/, '\1'
  inflect.singular /(?i-mx:s$)/, ''
  inflect.plural /(.*?)( of .*$)/i, '\1'.pluralize + ' \2'
  inflect.plural /(.*?)( for .*$)/i, '\1'.pluralize + ' \2'
  inflect.plural /(?i-mx:(z)ombies$)/, '\1ombies'
  inflect.plural /(?i-mx:(z)ombie$)/, '\1ombies'
  inflect.plural /(?i-mx:(m)oves$)/, '\1oves'
  inflect.plural /(?i-mx:(m)ove$)/, '\1oves'
  inflect.plural /(?i-mx:(s)exes$)/, '\1exes'
  inflect.plural /(?i-mx:(s)ex$)/, '\1exes'
  inflect.plural /(?i-mx:(c)hildren$)/, '\1hildren'
  inflect.plural /(?i-mx:(c)hild$)/, '\1hildren'
  inflect.plural /(?i-mx:(m)en$)/, '\1en'
  inflect.plural /(?i-mx:(m)an$)/, '\1en'
  inflect.plural /(?i-mx:(p)eople$)/, '\1eople'
  inflect.plural /(?i-mx:(p)erson$)/, '\1eople'
  inflect.plural /(?i-mx:(quiz)$)/, '\1zes'
  inflect.plural /(?i-mx:^(oxen)$)/, '\1'
  inflect.plural /(?i-mx:^(ox)$)/, '\1en'
  inflect.plural /(?i-mx:^(m|l)ice$)/, '\1ice'
  inflect.plural /(?i-mx:^(m|l)ouse$)/, '\1ice'
  inflect.plural /(?i-mx:(matr|vert|ind)(?:ix|ex)$)/, '\1ices'
  inflect.plural /(?i-mx:(x|ch|ss|sh)$)/, '\1es'
  inflect.plural /(?i-mx:([^aeiouy]|qu)y$)/, '\1ies'
  inflect.plural /(?i-mx:(hive)$)/, '\1s'
  inflect.plural /(?i-mx:(?:([^f])fe|([lr])f)$)/, '\1\2ves'
  inflect.plural /(?i-mx:sis$)/, 'ses'
  inflect.plural /(?i-mx:([ti])a$)/, '\1a'
  inflect.plural /(?i-mx:([ti])um$)/, '\1a'
  inflect.plural /(?i-mx:(buffal|tomat)o$)/, '\1oes'
  inflect.plural /(?i-mx:(bu)s$)/, '\1ses'
  inflect.plural /(?i-mx:(alias|status)$)/, '\1es'
  inflect.plural /(?i-mx:(octop|vir)i$)/, '\1i'
  inflect.plural /(?i-mx:(octop|vir)us$)/, '\1i'
  inflect.plural /(?i-mx:^(ax|test)is$)/, '\1es'
  inflect.plural /(?i-mx:s$)/, 's'
  inflect.plural /(?-mix:$)/, 's'
end