default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("RAILS_DATABASE_HOST") { 'postgres' } %>
  min_messages: WARNING
  password: <%= ENV.fetch("RAILS_DATABASE_PASSWORD") { 'password' } %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("RAILS_DATABASE_USER") { 'postgres' } %>

development:
  <<: *default
  database: openplaques_development

test:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB") { 'openplaques_test' } %>
